{PRODUCT_SHOP}{PRODUCT_SPECIAL_TYPE}
{PRODUCT_NAZV}
        
{PRODUCT_PRICE}
            
{PRODUCT_RATE}{PRODUCT_RATE_YN}

{PRODUCT_IMG}{PRODUCT_PAGE_BASKET}

{PRODUCT_CATS}
{PRODUCT_KEYWORDS}
                
{PRODUCT_ATTRS}
{PRODUCTION_CODE}
{PRODUCT_WEIGHT}
              
{PRODUCT_GRP_NAZV}
               
{PRODUCT_DESCR}
{PRODUCT_IMG_ALL}
        
{PRODUCT_CONNECTS}
{PRODUCT_IN_GRPS}

{RECOMENDATIONS}
{RECOMENDATIONS_KEYWORDS}
{RECOMENDATIONS_MANUF}
{RECOMENDATIONS_ATTR}
{RECOMENDATIONS_SAMECAT}

{SHOW_COMMENTS}{COMMENTS_FORM}